model_config:
  model_name: "bert-base-uncased"

data_config:
  model_name: "bert-base-uncased"
  max_len: 128
  valid_size: 0.1
  batch_size: 16

train_config:
  epochs: 5
  lr: 3e-5
  optimizer: "adamw"
  checkpoint_dir: "./checkpoints"
