_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.6
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
data_config:
    value:
        batch_size: 16
        max_len: 128
        model_name: bert-base-uncased
        valid_size: 0.1
model_config:
    value:
        model_name: bert-base-uncased
train_config:
    value:
        checkpoint_dir: ./checkpoints/bert-base-uncased
        epochs: 5
        lr: 5e-05
        optimizer: adam
