_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.6
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 4
epochs:
    value: 5
lr:
    value: 1e-05
max_len:
    value: 128
model_name:
    value: answerdotai/ModernBERT-base
num_labels:
    value: 2
test_size:
    value: 0.1
valid_size:
    value: 0.1
